version: '3.8'
name: coasters-dev
services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/var/www/html
    networks:
      - default

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/dev.conf:/etc/nginx/conf.d/default.conf

    depends_on:
      - php
    networks:
      - default
  redis:
    image: redis:7-alpine
    ports:
      - "63799:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: [ "redis-server", "--appendonly", "yes" ]
    networks:
      - default

volumes:
  redis_data: