version: '3.8'
name: coasters-prod
services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    environment:
      CI_ENVIRONMENT: production
    volumes:
      - .:/var/www/html
    networks:
      - default

  nginx:
    image: nginx:1.25
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/prod.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - default
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: [ "redis-server", "--appendonly", "yes" ]
    networks:
      - default

volumes:
  redis_data: